
apiVersion: v1          # La version de l'API Kubernetes à utiliser
kind: Namespace         # Le type d'objet qu'on crée : un Namespace
metadata:
  name: dashboard       # Le nom de votre "dossier" dans Kubernetes
