
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc      # Nom du disque qu'on réserve
  namespace: dashboard
spec:
  accessModes:
    - ReadWriteOnce       # Un seul Pod peut lire/écrire à la fois (normal pour une BDD)
  resources:
    requests:
      storage: 1Gi        # On demande 1 Go de stockage
