
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dashboard
spec:
  selector:
    app: frontend            # Redirige vers les Pods labellisés "app: frontend"

  ports:
    - port: 80               # Port interne du Service
      targetPort: 80         # Port de Nginx dans le conteneur
    

  type: LoadBalancer             # Accessible depuis l'extérieur du cluster
